version: "3"
services:
  npm:
    image: node:15.0.0
    user: node
    entrypoint: npm
    command: --help
    working_dir: /home/node/app
    volumes:
      - .:/home/node/app

  node:
    image: node:15.0.0
    user: node
    entrypoint: node
    command: --help
    working_dir: /home/node/app
    volumes:
      - .:/home/node/app

  npx:
    image: node:15.0.0
    user: node
    entrypoint: npx
    command: --help
    working_dir: /home/node/app
    volumes:
      - .:/home/node/app
