name: Build

on: [push]

jobs:
  build:
    name: Build the project
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the project
        uses: actions/checkout@v2

      - name: Install dependencies
        run: docker-compose run --rm --user root -T npm install

      - name: Build the library
        run: docker-compose run --rm --user root -T npm run build

      - name: Configure the user name
        run: git config user.name "Amin NAIRI"

      - name: Configure the user email
        run: git config user.email "nairi.amin@gmail.com"

      - name: Stage the new build
        run: git add .

      - name: Commit the changes
        run: git commit -m "production build" || true


      - name: Push the changes
        run: git push
