name: Code Style

on: [push, pull_request]

jobs:
  codestyle:
    name: Check the code style
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the project
        uses: actions/checkout@v2

      - name: Install dependencies
        run: make install

      - name: Check the code style
        run: make lint
