name: Package

on:
  push:
    branches:
      - next
      - latest

jobs:
  package:
    name: Build the project & publish the package to the NPM registry
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the project
        uses: actions/checkout@v2

      - name: Setup for the environment
        run: cp .env.example .env

      - name: Setup for the NODE_AUTH_TOKEN
        run: sed -i "s/NODE_AUTH_TOKEN=.*/NODE_AUTH_TOKEN=${{ secrets.NODE_AUTH_TOKEN }}/" .env

      - name: Install dependencies
        run: make install

      - name: Build the library
        run: make build

      - name: Publish the package
        run: 'make publish || true'
